@startuml
!include style.puml
skinparam ArrowFontStyle plain
actor User

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":CommandBox" as CommandBox UI_COLOR
participant ":ResultDisplay" as ResultDisplay UI_COLOR
participant ":PersonListPanel" as PersonListPanel UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

User -> CommandBox : handleCommandEntered()
activate CommandBox

CommandBox -> MainWindow : executeCommand("find n/john")
activate MainWindow

MainWindow -> LogicManager : execute("find n/john")
activate LogicManager

ref over LogicManager : execute "find n/john"

LogicManager --> MainWindow : r
deactivate LogicManager

MainWindow -> PersonListPanel : refreshHeaderLabels()
activate PersonListPanel
PersonListPanel --> MainWindow
deactivate PersonListPanel

MainWindow -> MainWindow : displayResult(r)
activate MainWindow

MainWindow -> ResultDisplay : setPersonList(r.foundPersons, r.description)
activate ResultDisplay

ResultDisplay -> ResultDisplay : hideFeedbackTextArea()
activate ResultDisplay
ResultDisplay --> ResultDisplay
deactivate ResultDisplay

ResultDisplay -> ResultDisplay : showResultListContainer()
activate ResultDisplay
ResultDisplay --> ResultDisplay
deactivate ResultDisplay

ResultDisplay -> ResultDisplay : updateDescriptionDisplay(r.description)
activate ResultDisplay
ResultDisplay --> ResultDisplay
deactivate ResultDisplay

ResultDisplay -> ResultDisplay : updatePersonList(r.foundPersons)
activate ResultDisplay
ResultDisplay --> ResultDisplay
deactivate ResultDisplay

ResultDisplay --> MainWindow
deactivate ResultDisplay

MainWindow --> MainWindow
deactivate MainWindow

MainWindow --> CommandBox
deactivate MainWindow

CommandBox -> CommandBox : commandTextField.setText("")
activate CommandBox
CommandBox --> CommandBox
deactivate CommandBox

User <-- CommandBox
deactivate CommandBox
@enduml
